services:
  - type: web
    name: learnquest-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && npm install --save-dev @types/bcryptjs @types/cors @types/multer && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true